apiVersion: apps/v1
kind: Deployment

metadata:
  name: classifier-api
  namespace: dog-classifier

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: classifier-api

  template:
    metadata:
      labels:
        app: classifier-api

    spec:
      containers:

      - name: classifier-api

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        envFrom:
        - configMapRef:
            name: classifier-config

        ports:
        - containerPort: 8000
      
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"