apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: classifier-api
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - dog-classifier

  selector:
    matchLabels:
      app: classifier-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s