{
 "title": "Dog Breed Classifier Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Prediction Failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_failures_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Prediction Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[5m])\r\n/\r\nrate(prediction_latency_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}